config1:
  optimizer: 'adam'
  batchSize: 8
  epochs: 30
  autoencoderArch: 'normal'
  autoencoderModel: 'twoClassTest'
  classifierModel: 'simple'
  
config2:
  optimizer: 'adam'
  batchSize: 8
  epochs: 30
  autoencoderArch: 'normal'
  autoencoderModel: 'twoClassTest'
  classifierModel: 'fullyConnected1'