config00:
  optimizer: 'adam'
  batchSize: 8
  epochs: 2
  lossFunction: 'binary_crossentropy'
  segmentationArch: 'miniUnet'
  segmentationScheme: 'foregroundBackground'

config1:
  optimizer: 'adam'
  batchSize: 8
  epochs: 30
  lossFunction: 'binary_crossentropy'
  segmentationArch: 'miniUnet'
  segmentationScheme: 'foregroundBackground'

config2:
  optimizer: 'adam'
  batchSize: 8
  epochs: 30
  lossFunction: 'binary_crossentropy'
  segmentationArch: 'midiUnet'
  segmentationScheme: 'foregroundBackground'

config3:
  optimizer: 'adam'
  batchSize: 8
  epochs: 2
  lossFunction: 'binary_crossentropy'
  segmentationArch: 'miniUnet'
  segmentationScheme: 'personOnly'

config4:
  optimizer: 'adam'
  batchSize: 8
  epochs: 30
  lossFunction: 'binary_crossentropy'
  segmentationArch: 'miniUnet'
  segmentationScheme: 'personOnly'

config5:
  optimizer: 'adam'
  batchSize: 8
  epochs: 30
  lossFunction: 'binary_crossentropy'
  segmentationArch: 'midiUnet'
  segmentationScheme: 'personOnly'